# ---------------- #
#   Main Configs   #
# ---------------- #
title: 背包
author: 背包
subtitle: "Nothing is impossible to a willing heart!"
description: "不忘初心，砥砺前行......"
keywords: 背包
url: "https://blog.cn7seven.com"
date_format: "ordinal"
favicon: /favicon.ico
timezone: Asia/Chongqing
encoding: "utf-8"
source_code: https://github.com/cqzk/blog
side_bar_repo_limit: 5

# Site settings
baseurl: "http://blog.cn7seven.com" # the subpath of your site, e.g. /blog
#url: "" # the name of your domain
logo_url: favicon.ico

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Footer
copyright: © 2017 背包 - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:


# ---------------- #
#      Author      #
# ---------------- #
organization: cqzk, Inc.
organization_url: http://www.cqzk.com.cn
location: Chongqing, China
email: majh.cq@gmail.com

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: DentistSmile
    hero_description: A responsive Jekyll theme for dental clinics.

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories
    label: 分类

  -
    href: /wiki
    label: 维基
  

  -
    href: /open-source
    label: 开源

  -
    href: /blog
    label: 博客

  -
    href: /about
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-sitemap
#    - jekyll-seo-tag
#    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
#    - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: cqzk
facebook_username: cqzk1234
twitter_username: cqzk

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: cqzk

# ---------------- #
#    Analytics     #
# ---------------- #
##google:
##    analytics_id: UA-82387173-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, shell,Docker,Linux]
skill_mobile_app_keywords: [Java]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: cqzk/blog
